<a href="https://colab.research.google.com/github/Shiv751/100_Days_Of_ML_Code/blob/master/Day_2__Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Day - 2 | Introduction to Numpy Library
# @Author - Shivam Bharadwaj
# @GitHub - https://github.com/Shiv751/
# @linkedin - https://in.linkedin.com/in/meetshivambharadwaj
#100DaysOfMLCode



---


Numpy is the core library for scientific computing in Python.
It provides a high-performance multidimensional array object, and tools for working with these arrays. 
If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.


---



In [0]:
import numpy as np     #Import module Numpy and using it as 'np'

In [3]:
np.__version__

'1.14.6'

In [4]:
list = [1,2,3,4,5,6]      #Create a list of integers
list

[1, 2, 3, 4, 5, 6]

In [5]:
print(type(list))   #Check its type

<class 'list'>


In [6]:
npArray = np.array(list)  #We can create numpy array by passing a list like -  np.array(list)
print(npArray)                    #Here we are creating 1D array

[1 2 3 4 5 6]


In [7]:
print(type(npArray))   #Check its type
                       #Numpy allows to create n-dimentional arrays like 2D, 3D,4D......1056D etc
print(npArray.shape)   #Prints shape like (Rows, Columns)

<class 'numpy.ndarray'>
(6,)


In [8]:
list2 = [5,6,7,8,9]      #Create a list of integers
list2

[5, 6, 7, 8, 9]

In [9]:
two_D_Array = np.array([[list,list2]])  #We can create numpy array by passing a list like -  np.array(list)
print(two_D_Array) 

[[list([1, 2, 3, 4, 5, 6]) list([5, 6, 7, 8, 9])]]


In [10]:
b = np.array([list,list2])
print(b)

[list([1, 2, 3, 4, 5, 6]) list([5, 6, 7, 8, 9])]


In [11]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[0. 0.]
 [0. 0.]]


In [12]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"


[[1. 1.]]


In [13]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[7 7]
 [7 7]]


In [14]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[1. 0.]
 [0. 1.]]


In [15]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0.08619191 0.88303332]
 [0.25325012 0.29487982]]


In [16]:
f = np.random.rand(2,3)  # Create an array filled with random values
print(f)                    
                           

[[0.62474773 0.47101917 0.47982693]
 [0.91995738 0.49110827 0.71313231]]


In [17]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]

b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [19]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

print(a[0, 1])   # Prints "2" i.e a[Row, Corresponding_Column_No]
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]      <-- **Attention Required**
print(a[0, 1])   # Prints "77"

2
77


In [20]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [21]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and

print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

[1 4 5]
[1 4 5]


In [22]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]


In [23]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

int64


In [24]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

219
219
[29 67]
[29 67]


In [25]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [26]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

m = np.reshape(v, (3, 1)) * w    #Reshape v into 3 rows and 1 column and multipy 
                                    # result by w i.e(4,5) in each row
print(m)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [27]:
print(m.T)  #Prints transpose of matrix

[[ 4  8 12]
 [ 5 10 15]]
